// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uuzbqkiobqhkmpmkvmbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1emJxa2lvYnFoa21wbWt2bWJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwOTcwMjAsImV4cCI6MjA3MTY3MzAyMH0.j1bCo0COQfS5iCxlEK6eoaqVzj4TK1h_2jF4BU-xwvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);